[audio_parser]
bitrate = 131
duration = 233
file_format = 'mp3'
file_format_long = 'MP2/3 (MPEG audio layer 2/3)'
path = '../../sample2.mp3'

[metadata]
TSRC = 'GBAYE9400058'
album = 'The Bends'
album_artist = 'Radiohead'
artist = 'Radiohead'
comment = 'https://music.youtube.com/watch?v=jIjTFt6XmFM'
copyright = '1995 XL Recordings Ltd'
date = '1995'
disc = '1/1'
encoded_by = 'XL Recordings'
encoder = 'Lavf61.7.100'
genre = 'Alternative Rock'
title = '(Nice Dream)'
track = '6/12'

[stream_0]
bitrate = 128
channel_layout = 'stereo'
channels = 2
codec = 'mp3'
sample_format = 'fltp'
sample_rate = 48000
type = 'Audio'

[stream_1]
codec = 'mjpeg'
type = 'Video'
