[audio_parser]
bitrate = 131
bitrates = [ 64005, 112008, 128010 ]
duration = 337
file_format = 'mp3'
file_format_long = 'MP2/3 (MPEG audio layer 2/3)'
path = 'sample.mp3'

[metadata]
TSRC = ''
album = 'From Mars to Sirius'
album_artist = 'Gojira'
artist = 'Gojira'
comment = 'https://music.youtube.com/watch?v=BuXOmxGlzwI'
copyright = '2005 Listenable Records'
date = '2005'
disc = '1/1'
encoded_by = 'Listenable records'
encoder = 'Lavf61.7.100'
genre = 'Metal'
title = 'To Sirius'
track = '11/12'

[stream_0]
bitrate = 128
channel_layout = 'stereo'
channels = 2
codec = 'mp3'
sample_format = 'fltp'
sample_rate = 48000
type = 'Audio'

[stream_1]
bitrate = 128
channel_layout = ''
channels = 2
codec = 'mjpeg'
sample_format = ''
sample_rate = 48000
type = 'Video'
