name: Docker Build & Test for Wavy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t wavy-server-test .

      - name: Run Container
        run: |
          docker run -d --name wavy-server -p 8080:8080 wavy-server-test

      - name: Get Container ID
        run: echo "CONTAINER_ID=$(docker ps -q --filter "name=wavy")" >> $GITHUB_ENV

      - name: Test Server Response (Inside Container)
        run: |
          RESPONSE=$(docker exec $CONTAINER_ID curl -k -sSf https://localhost:8080/hls/ping)
          if [[ "$RESPONSE" == "pong" ]]; then
            echo "-- Server is running and responded with 'pong'!"
          else
            echo "**Unexpected response: $RESPONSE**" && exit 1
          fi

      - name: Stop and Remove Container
        run: docker stop wavy-server && docker rm wavy-server
