name: Clang Tidy Check for Wavy (x86-64 arch Ubuntu)

on:
  push:
    branches: [ "main" ]  # Trigger on push to the 'main' branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy make wget

    - name: Run Clang Tidy check for Wavy
      run: |
        make init
        make tidy
