name: Clang Tidy Check for Wavy (x86-64 arch Ubuntu)

on:
  push:
    branches: [ "main" ]  # Trigger on push to the 'main' branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy make wget

    - name: Install dependencies for Wavy
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libflac++-dev libboost-log-dev libboost-system-dev libboost-filesystem-dev libssl-dev \
          libavformat-dev libavutil-dev libswresample-dev libavcodec-dev \
            libzstd-dev \
            cmake make pkg-config \
            libarchive-dev \
            libmp3lame-dev

    - name: Compile Wavy for x86-64 Ubuntu
      run: |
        make

    - name: Run Clang Tidy check for Wavy
      run: |
        make tidy
